name: Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    name: Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: lint-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          lint-pip-

    - name: pre-commit cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: lint-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
        restore-keys: |
          lint-pre-commit-

    - name: Set up Python ${{ matrix.python-version }}
      uses: MatteoH2O1999/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      env:
        PIP_INDEX_URL: https://eyJjb2RlY292IjogIjIuMS4xMyIsICJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io
    - name: Build system information
      run: python .github/workflows/system-info.py

    - name: Install dependencies
      run: |
        python -m pip install --index-url 'https://:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io/' --upgrade pip
        python -m pip install --index-url 'https://:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io/' --upgrade tox

    - name: Lint
      run: tox -e lint
      env:
        PRE_COMMIT_COLOR: always
        PIP_INDEX_URL: https://eyJjb2RlY292IjogIjIuMS4xMyIsICJhdG9taWN3cml0ZXMiOiAiMS4wLjAifQ==:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io
